### ISSUE TITLE
librtasevent.so has underfined symbols using musl

### ISSUE THREAD

**Issue by grobian** [ibm-power-utilities/librtas#10]
Linking against librtasevent fails with undefined symbols for be16toh and be32toh.  The reason for this is that with musl, one needs to include <endian.h> for the beXtoh macros.  Doing so in the source, squashes the compiler warnings and ensures no undefined symbols are in the library.

I just added #include <endian.h> to librtasevent_src/rtas_event.h, but that may be a bit too crude.

**Comment by hegdevasant** [comment]
>  librtasevent_src/rtas_event.

This seems to be the right thing to do. I'm surprised why it didn't show up till now.

Do you mind sending patch/creating PR?

-Vasant

**Comment by grobian** [comment]
sure, let me create a PR
