### ISSUE TITLE
deprecate rtas_delay_timeout?

### ISSUE THREAD

**Issue by nathanlynch** [ibm-power-utilities/librtas#14]
Despite its description, the `rtas_delay_timeout` function *sets* an internal timeout value:

```
/**
 * rtas_delay_timeout
 * @brief Interface to retrieve the rtas timeout delay
 *
 * @param timeout_ms timeout in milli-seconds
 * @return delay time
 */
int rtas_delay_timeout(uint64_t timeout_ms)
{
	int rc;

	rc = sanity_check();
	if (rc)
		return rc;

	rtas_timeout_ms = timeout_ms;

	return 0;
}
```
This timeout is used to cut short the logic in `handle_delay` after the timeout has elapsed. Fortunately this is unused by default. I'm not seeing a good reason to support this. The library should run all operations to completion, otherwise we risk leaving things in unrecoverable states.

I haven't found any users of it with a github search. Probably shouldn't remove it outright, but we could change it to do nothing and document this.

**Comment by tyreld** [comment]
Could always hit it with a `__attribute__ ((deprecated))` to start with.

**Comment by tyreld** [comment]
Marked deprecated with commit https://github.com/ibm-power-utilities/librtas/commit/e7eff65e74ebe268a184d53d5fe94ebff5f7b4eb
