### ISSUE TITLE
configure.ac LOCAL_CHECK_FLAGS is problematic

### ISSUE THREAD

**Issue by tpetazzoni** [ibm-power-utilities/librtas#25]
The flags added by ```LOCAL_CHECK_FLAGS``` in ```configure.ac``` are problematic for build systems such as Buildroot.

First of all, the addition of ```-fstack-protector-all``` is done based on just a compiler test (aka ```gcc -c```), but there are cases where only a full link test is needed to make sure SSP works. Due to that, with uClibc toolchains that don't have SSP support enabled, we get a build failure:
```
/home/thomas/projets/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/powerpc-buildroot-linux-uclibc/10.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld: cannot find -lssp_nonshared
/home/thomas/projets/buildroot/output/host/opt/ext-toolchain/bin/../lib/gcc/powerpc-buildroot-linux-uclibc/10.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld: cannot find -lssp
collect2: error: ld returned 1 exit status
```
More generally, setting such flags unconditionally conflicts with policies defined by build systems. Buildroot has options to decide whether SSP should be used or not, whether RELRO should be used or not. At least an option to disable the addition of such flags would be useful, like --disable-hardening of something similar.

**Comment by nathanlynch** [comment]
Thanks for the thorough report. I agree we should stop unconditionally setting CFLAGS and LDFLAGS in configure.ac by default.

**Comment by tyreld** [comment]
Fixed by upstream commit https://github.com/ibm-power-utilities/librtas/commit/1116a74b8ed01722957098eb934c0a8c186e2b27
