### ISSUE TITLE
librtas should immediately retry without sleeping on -2 call status

### ISSUE THREAD

**Issue by nathanlynch** [ibm-power-utilities/librtas#30]
Explanation here:

https://github.com/torvalds/linux/commit/38f7b7067dae0c101be573106018e8af22a90fdf

> RTAS_BUSY (-2): RTAS has suspended a potentially long-running operation in
order to meet its latency obligation and give the OS the opportunity to
perform other work. RTAS can resume making progress as soon as the OS
reattempts the call.

There is no need to delay before retrying on -2. The kernel used to get this wrong too. librtas should update its behavior to avoid uselessly sleeping. Looks like `handle_delay` could be tweaked to return `CALL_AGAIN` immediately when it is passed -2.

**Comment by tyreld** [comment]
Fixed by commit https://github.com/ibm-power-utilities/librtas/commit/238bf041152b78aa0d9dce813d360ea0731c128c
