### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ibm-power-utilities/librtas#4]
I would like to point out that identifiers like “[`_LIBRTAS_H_`](https://github.com/nfont/librtas/blob/90f24679c795ea8224ba836994366dec31529663/librtas_src/librtas.h#L23 "Update candidate")” and “[`__NR_rtas`](https://github.com/nfont/librtas/blob/af07fde662985cb574fe56497847c4c6cdf1d1a8/librtas_src/syscall.h#L28 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by nathanlynch** [comment]
I agree the header guards are worth making compliant.

We could avoid defining `__NR_rtas` too -- at this point surely we're not being built against kernel headers that lack it?

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/ibm-power-utilities/librtas/commit/9077f0833cc06606897cb023accac9ba268dad48 "Avoid reserved names for inclusion guards in shipped headers").
