### ISSUE TITLE
librtas.h (re)defines PAGE_SIZE

### ISSUE THREAD

**Issue by nathanlynch** [ibm-power-utilities/librtas#7]
System headers potentially define PAGE_SIZE and librtas.h should not unconditionally redefine it.

**Comment by tyreld** [comment]
I think prefixing it with RTAS_ would suffice. PAPR refers to the work area as 4096 byte pages. So, adding the prefix keeps consistent with PAPR that RTAS pages are 4k and it becomes clear we aren't referring to system PAGE_SIZE. Oh, and of course we avoid clobbering a system header define of PAGE_SIZE.

**Comment by nathanlynch** [comment]
Yes, I think RTAS_PAGE_SIZE or similar is fine, and kept in an internal header.
